CMD_INTERNAL_AUTH           = "cmd_internal_auth"
CMD_LOGIN                   = "cmd_login"
CMD_USER_LIST               = "cmd_user_list"    
MSG_USER_LIST               = "msg_user_list"         
CMD_CREATE_USER             = "cmd_create_user"       
MSG_CREATE_USER             = "msg_create_user"       
CMD_SELECT_USER             = "cmd_select_user"       
MSG_ENTER_GAME              = "msg_enter_game"        
MSG_LOGIN_NOTIFY_STATUS     = "msg_login_notify_status"
NEW_CLIENT_INIT             = "new_client_init"
LOSE_CLIENT                 = "lose_client"
CMD_COMMON_OP               = "cmd_common_op"
MSG_COMMON_OP               = "msg_common_op"
MSG_OBJECT_UPDATED          = "msg_object_updated"
MSG_PROPERTY_LOADED         = "msg_property_loaded"
MSG_BONUS                   = "msg_bonus"
CMD_SALE_OBJECT             = "cmd_sale_object"
MSG_SALE_OBJECT             = "msg_sale_object"
MSG_PROPERTY_DELETE         = "msg_property_delete"
CMD_CHAT                    = "cmd_chat"
MSG_CHAT                    = "msg_chat"



MSG_DB_RESULT               = "msg_db_result"