CMD_INTERNAL_AUTH           = "cmd_internal_auth"
CMD_LOGIN                   = "cmd_login"
CMD_USER_LIST               = "cmd_user_list"    
MSG_USER_LIST               = "msg_user_list"         
CMD_CREATE_USER             = "cmd_create_user"       
MSG_CREATE_USER             = "msg_create_user"       
CMD_SELECT_USER             = "cmd_select_user"       
MSG_ENTER_GAME              = "msg_enter_game"        
MSG_LOGIN_NOTIFY_STATUS     = "msg_login_notify_status"
NEW_CLIENT_INIT             = "new_client_init"
LOSE_CLIENT                 = "lose_client"

MSG_DB_RESULT               = "msg_db_result"